name: Build pacman package
on:
  workflow_call:
    inputs:
      package-name:
        description: 'AUR package to build'
        required: true
        type: string
          
  workflow_dispatch:
    inputs:
      package-name:
        description: 'AUR package to build'
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the package builder docker image
        working-directory: builder
        run: docker build . --tag builder:latest

      - name: Run the package builder docker image
        working-directory: builder
        run: |
          docker run -i \
          -e GITHUB_KEY=${{ github.token }} \
          -e REPO=${{ github.repository }} \
          -e PKG_NAME=${{ inputs.package-name }} \
          builder:latest
