name: Build pacman package
on: [workflow_call, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for PACKAGE_NAME variable exists
        if: ${{ vars.PACKAGE_NAME == '' }}
        run: |
          echo "error: PACKAGE_NAME is not declared in reposirory's variables."
          exit 1

      - name: Build the package builder docker image
        working-directory: builder
        run: docker build . --tag builder:latest

      - name: Run the package builder docker image
        working-directory: builder
        run: |
          docker run -i \
          -e GITHUB_KEY=${{ github.token }} \
          -e REPO=${{ github.repository }} \
          -e PKG_NAME=${{ vars.PACKAGE_NAME }} \
          -e MAKEPKG_ENV_VARS=${{ vars.MAKEPKG_ENV_VARS }} \
          builder:latest
